apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: 929163871313.dkr.ecr.us-east-1.amazonaws.com/demoapp/php:<TAG>
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer